// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coagqeqodswmjeehvyod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWdxZXFvZHN3bWplZWh2eW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzkyNDUsImV4cCI6MjA3MDY1NTI0NX0.rbv0sMK5q-6-10gqtgsETQvKmXR4giCDwnWIbiDShy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});